In [ ]:
import numpy as np
import pandas as pd

Given:
$$
n=3,\space a_0=0,\space a_1=1,\space a_2=1/2,\space a_3=-2
$$

Create a vector $\textbf{x} ∈ \mathbb{R}^m$ of $m = 10,000$ measurement points randomly sampled from a uniform distribution over the section [-1,1]

In [ ]:
m = 10000
x = np.random.uniform(low=-1, high=1, size=m)
x

array([ 0.92679979, -0.87633142, -0.61541365, ..., -0.17630925,
        0.09273282,  0.09854086])

For this vector $x$ calculate $f(x_i)=a_0+a_1x_i+a_2x_i^2+a_3x_i^3,\space i=1,2,...,m$

In [ ]:
a_0 = 0
a_1 = 1
a_2 = 1/2
a_3 = -2

f = a_0 + a_1 * x + a_2 * x**2 + a_3 * x**3
f

array([-0.2358852 ,  0.85361622,  0.04010944, ..., -0.14980565,
        0.09543762,  0.10148229])

Create the vector $\textbf{y}$, where $y_i=f(x_i)+w_i, \space i=1,2,...,m$ by adding Gaussian noise $w_i$ with variance $σ^2 = 0.5$ to each of the measurements.

In [ ]:
variance = 0.5
w = np.random.normal(loc=0, scale=np.sqrt(variance), size=m)
y = f + w
y

array([-0.59657495,  1.56422622, -0.82088978, ..., -0.90067645,
        0.18780733,  0.2278615 ])

#**Part 1**